### ISSUE TITLE
Linux Installer: python3 string issues in text mode

### ISSUE THREAD

**Issue by egroeper** [GEANT/CAT#133]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [x] Defect - Crash/memory corruption.
# Defect/Feature description

Problem with python3 compatibility (string handling) in text mode.

## How to reproduce issue

* Force text mode: `unset DISPLAY` in terminal
* run installer: `python3 main.py`
 
## Detail of issue

```text
python3 --version
Python 3.6.6

environment:
LANG="de_DE.UTF-8"

python3 main.py 
Dieses Installationsprogramm wurde für Humboldt-Universität zu Berlin hergestellt.

Mehr Informationen und Kommentare:

EMAIL: <our email>
WWW: <url>

Das Installationsprogramm wurde mit Software vom GEANT Projekt erstellt.

-------
Dieses Installationsprogramm funktioniert nur für Anwender von Humboldt-Universität zu Berlin.

Weiter? (J/N) [J]

-------
Directory /home/user/.cat_installer exists; some of its files may be overwritten.

Weiter? (J/N) [J]
Geben Sie ihre Benutzerkennung ein: test
Traceback (most recent call last):
  File "test.py", line 754, in <module>
    run_installer()
  File "test.py", line 71, in run_installer
    inst.get_user_cred()
  File "test.py", line 277, in get_user_cred
    self.__get_username_password()
  File "test.py", line 295, in __get_username_password
    self.USERNAME = self.prompt_nonempty_string(1, Messages.username_prompt, user_prompt)
  File "test.py", line 240, in prompt_nonempty_string
    output = inp.strip().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by twoln** [comment]
Yes, I am aware of that and it is on my TODO list. Thanks.

**Comment by twoln** [comment]
fixed

**Comment by hettipeti** [comment]
So whats the fix?
It seems still not deployed on https://cat.eduroam.org/
Getting still the error on commandine :-)

**Comment by twoln** [comment]
See main_new.py, this is a rather extensive rewrite of the script based on multiple comments on GitHub. 
The easiest way to use it is to change the script name in Device_Linux.php. Since the new scrip is not tested very extensively it seemed safer to keep both versions for a while.

**Comment by hettipeti** [comment]
You probably mean Device_Linux.py? :-)
Interesting, this worked for my Fedora installation, but on Arch I did the same and Im getting the same error :(

**Comment by twoln** [comment]
I was commenting on the code as it is. On cat.eduroam.org we will do some updates in the near future.

**Comment by hettipeti** [comment]
Temporal Fix for all the user out there that want to run it.
`244                output = inp.strip().decode('utf-8')
`

remove the .decode('utf-8'):
`244                output = inp.strip()
`

See also https://stackoverflow.com/a/28583969

**Comment by ikreb7** [comment]
Well, I think the problem of @hettipeti is that the bug at ``main.py`` isn't still fixed. So the question is whether it's right to close this issue as long the ``main.py`` is used at cat.eduroam.org.
